onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /testbench_top/dut/HRESETn
add wave -noupdate /testbench_top/dut/HCLK
add wave -noupdate /testbench_top/dut/pma_cfg_i
add wave -noupdate /testbench_top/dut/pma_adr_i
add wave -noupdate /testbench_top/dut/ins_HSEL
add wave -noupdate /testbench_top/dut/ins_HADDR
add wave -noupdate /testbench_top/dut/ins_HWDATA
add wave -noupdate /testbench_top/dut/ins_HRDATA
add wave -noupdate /testbench_top/dut/ins_HWRITE
add wave -noupdate /testbench_top/dut/ins_HSIZE
add wave -noupdate /testbench_top/dut/ins_HBURST
add wave -noupdate /testbench_top/dut/ins_HPROT
add wave -noupdate /testbench_top/dut/ins_HTRANS
add wave -noupdate /testbench_top/dut/ins_HMASTLOCK
add wave -noupdate /testbench_top/dut/ins_HREADY
add wave -noupdate /testbench_top/dut/ins_HRESP
add wave -noupdate /testbench_top/dut/dat_HSEL
add wave -noupdate /testbench_top/dut/dat_HADDR
add wave -noupdate /testbench_top/dut/dat_HWDATA
add wave -noupdate /testbench_top/dut/dat_HRDATA
add wave -noupdate /testbench_top/dut/dat_HWRITE
add wave -noupdate /testbench_top/dut/dat_HSIZE
add wave -noupdate /testbench_top/dut/dat_HBURST
add wave -noupdate /testbench_top/dut/dat_HPROT
add wave -noupdate /testbench_top/dut/dat_HTRANS
add wave -noupdate /testbench_top/dut/dat_HMASTLOCK
add wave -noupdate /testbench_top/dut/dat_HREADY
add wave -noupdate /testbench_top/dut/dat_HRESP
add wave -noupdate /testbench_top/dut/ext_nmi
add wave -noupdate /testbench_top/dut/ext_tint
add wave -noupdate /testbench_top/dut/ext_sint
add wave -noupdate /testbench_top/dut/ext_int
add wave -noupdate /testbench_top/dut/dbg_stall
add wave -noupdate /testbench_top/dut/dbg_strb
add wave -noupdate /testbench_top/dut/dbg_we
add wave -noupdate /testbench_top/dut/dbg_addr
add wave -noupdate /testbench_top/dut/dbg_dati
add wave -noupdate /testbench_top/dut/dbg_dato
add wave -noupdate /testbench_top/dut/dbg_ack
add wave -noupdate /testbench_top/dut/dbg_bp
add wave -noupdate /testbench_top/dut/if_stall_nxt_pc
add wave -noupdate /testbench_top/dut/if_nxt_pc
add wave -noupdate /testbench_top/dut/if_stall
add wave -noupdate /testbench_top/dut/if_flush
add wave -noupdate /testbench_top/dut/if_parcel
add wave -noupdate /testbench_top/dut/if_parcel_pc
add wave -noupdate /testbench_top/dut/if_parcel_valid
add wave -noupdate /testbench_top/dut/if_parcel_misaligned
add wave -noupdate /testbench_top/dut/if_parcel_page_fault
add wave -noupdate /testbench_top/dut/dmem_req
add wave -noupdate /testbench_top/dut/dmem_adr
add wave -noupdate /testbench_top/dut/dmem_size
add wave -noupdate /testbench_top/dut/dmem_we
add wave -noupdate /testbench_top/dut/dmem_d
add wave -noupdate /testbench_top/dut/dmem_q
add wave -noupdate /testbench_top/dut/dmem_ack
add wave -noupdate /testbench_top/dut/dmem_err
add wave -noupdate /testbench_top/dut/dmem_misaligned
add wave -noupdate /testbench_top/dut/dmem_page_fault
add wave -noupdate /testbench_top/dut/st_prv
add wave -noupdate /testbench_top/dut/st_pmpcfg
add wave -noupdate /testbench_top/dut/st_pmpaddr
add wave -noupdate /testbench_top/dut/cacheflush
add wave -noupdate /testbench_top/dut/dcflush_rdy
add wave -noupdate /testbench_top/dut/ibiu_stb
add wave -noupdate /testbench_top/dut/ibiu_stb_ack
add wave -noupdate /testbench_top/dut/ibiu_d_ack
add wave -noupdate /testbench_top/dut/ibiu_adri
add wave -noupdate /testbench_top/dut/ibiu_adro
add wave -noupdate /testbench_top/dut/ibiu_size
add wave -noupdate /testbench_top/dut/ibiu_type
add wave -noupdate /testbench_top/dut/ibiu_we
add wave -noupdate /testbench_top/dut/ibiu_lock
add wave -noupdate /testbench_top/dut/ibiu_prot
add wave -noupdate /testbench_top/dut/ibiu_d
add wave -noupdate /testbench_top/dut/ibiu_q
add wave -noupdate /testbench_top/dut/ibiu_ack
add wave -noupdate /testbench_top/dut/ibiu_err
add wave -noupdate /testbench_top/dut/dbiu_stb
add wave -noupdate /testbench_top/dut/dbiu_stb_ack
add wave -noupdate /testbench_top/dut/dbiu_d_ack
add wave -noupdate /testbench_top/dut/dbiu_adri
add wave -noupdate /testbench_top/dut/dbiu_adro
add wave -noupdate /testbench_top/dut/dbiu_size
add wave -noupdate /testbench_top/dut/dbiu_type
add wave -noupdate /testbench_top/dut/dbiu_we
add wave -noupdate /testbench_top/dut/dbiu_lock
add wave -noupdate /testbench_top/dut/dbiu_prot
add wave -noupdate /testbench_top/dut/dbiu_d
add wave -noupdate /testbench_top/dut/dbiu_q
add wave -noupdate /testbench_top/dut/dbiu_ack
add wave -noupdate /testbench_top/dut/dbiu_err
add wave -noupdate /testbench_top/dut/if_parcel_error
add wave -noupdate /testbench_top/dut/dmem_lock
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ns} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {1 us}
